import { OperatorList } from './operator.constant';

export const DATA_TYPE = {
    TEXT: 'text',
    NUMBER: 'number',
    BOOLEAN: 'boolean',
    DATE: 'date',
    DATE_TIME: 'date_time',
    DATE_LATERAL: 'date_lateral',
    REFERENCE: 'reference_select',
    SELECT: 'select',
    CURRENCY: 'currency',
} as const;

export type OperatorType = (typeof OperatorList)[number]['name'];

export type DataTypeType = (typeof DATA_TYPE)[keyof typeof DATA_TYPE];
type DataOperatorsType = { [key in DataTypeType]?: OperatorType[] };

export const DATA_OPERATORS: DataOperatorsType = {
    [DATA_TYPE.TEXT]: [
        '=',
        '!=',
        'like',
        'not like',
        // 'in',
        // 'not in',
        'notNull',
        'null',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.BOOLEAN]: ['=', '!=', 'notNull', 'null'],
    [DATA_TYPE.NUMBER]: [
        '=',
        '!=',
        '<',
        '>',
        '<=',
        '>=',
        'between',
        'notBetween',
        // 'in',
        // 'not in',
        'null',
        'notNull',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.CURRENCY]: [
        '=',
        '!=',
        '<',
        '>',
        '<=',
        '>=',
        'between',
        'notBetween',
        // 'in',
        // 'not in',
        'null',
        'notNull',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.DATE]: [
        '=',
        '!=',
        '<',
        '>',
        '<=',
        '>=',
        'between',
        'notBetween',
        // 'in',
        // 'not in',
        'null',
        'notNull',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.DATE_TIME]: [
        // '=',
        // '!=',
        '<',
        '>',
        '<=',
        '>=',
        'between',
        'notBetween',
        'null',
        'notNull',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.REFERENCE]: [
        '=',
        '!=',
        'null',
        'notNull',
        'in',
        'notIn',
        'contains',
        'not contains',
        'matches',
        'not matches',
    ],
    [DATA_TYPE.SELECT]: ['=', '!='],
    [DATA_TYPE.DATE_LATERAL]: ['=', '!=', '<', '>', '<=', '>='],
};
