export const SET_CURRENT_BUSINESS = 'SET_CURRENT_BUSINESS';
export const CURRENT_BUSINESS = 'CURRENT_BUSINESS';
export const BUSINESSES = 'BUSINESSES';
export const SALES_BUSINESSES = 'SALES_BUSINESSES';
export const USER = 'USER';
export const SHOW_TOAST = 'SHOW_TOAST';
export const SHOW_ACTION_TOAST = 'SHOW_ACTION_TOAST';
export const LOADER = 'LOADER';
export const NET_CONNECTION = 'NET_CONNECTION';
export const SHOW_OFFLINE_VIEW = 'SHOW_OFFLINE_VIEW';
export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const FIRST_TIME_APP_LAUNCH_KEY = 'FIRST_TIME_APP_LAUNCH_KEY';

export const ANALYTICS_EVENT = 'ANALYTICS_EVENT';

export const LOGIN_WHATS_APP_TOKEN = 'LOGIN_WHATS_APP_TOKEN';

export const SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG';

export const INTEGRATION_LIST = 'INTEGRATIONS';
export const OPEN_SPOTLIGHT = 'OPEN_SPOTLIGHT';
export const CLOSE_SPOTLIGHT = 'CLOSE_SPOTLIGHT';

export const OPEN_ADD_CLIENT_ONBOARDING = 'OPEN_ADD_CLIENT_ONBOARDING';
