FROM node:18-alpine AS base

FROM base AS builder
RUN apk add --no-cache libc6-compat
RUN apk update

# Set working directory
WORKDIR /app/web
RUN yarn global add turbo@1.10.16
RUN yarn add sharp
COPY . .
RUN turbo prune --scope=@finnoto/web --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app/web

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/web/out/json/ .
COPY --from=builder /app/web/out/yarn.lock ./yarn.lock
RUN yarn install

# Build the project
COPY --from=builder /app/web/out/full/ .
RUN yarn turbo run build --filter=@finnoto/web...

FROM base AS runner
WORKDIR /app/web

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/web/apps/web/next.config.js .
COPY --from=installer /app/web/apps/web/package.json .

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/web/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/web/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/web/apps/web/public ./apps/web/public

# CMD [ "node", "apps/web/server.js" ]