export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const U_DEVICE_IDENTIFIER = 'U_DEVICE_IDENTIFIER';

export const MENU_LIST = 'MENUS';
export const RECENT_STATE = 'recentState';
export const BACKEND_URL = 'BACKEND_URL';
export const BUSINESS_API_HISTORY = 'BUSINESS_API_HISTORY';
export const ORGANIZATION_NAME = 'ORGANIZATION_NAME';
