name: Testing

on:
    push:
        branches: [main]
    pull_request:
        branches: [main, pre-release, release-*]
jobs:
    testing:
        runs-on: ubuntu-latest
        env:
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: yarn install --immutable
            - run: yarn build:packages
            - run: yarn test
